const mtasQuestions = [
  { text: "Before a test/exam, I am worried I will fail.", score: 0 },
  { text: "I forget previously known material before taking a test/exam.", score: 0 },
  { text: "Even when I have prepared for a test/exam I feel nervous about it.", score: 0 },
  { text: "Before I take a test/exam my hand trembles.", score: 0 },
  { text: "During tests/exams, I worry about the consequences of failing.", score: 0 },
  { text: "I forget facts I have learnt during tests/exams.", score: 0 },
  { text: "I feel tense before taking a test/exam.", score: 0 },
  { text: "My heart races when I take a test/exam.", score: 0 },
  { text: "After a test/exam, I am worried I have failed.", score: 0 },
  { text: "During tests/exams, I forget things that I have learnt.", score: 0 },
  { text: "Just before I take a test/exam, I feel panicky.", score: 0 },
  { text: "During a test/exam I experience stomach discomfort.", score: 0 },
  { text: "During a test/exam, I worry that I gave the wrong answers.", score: 0 },
  { text: "During tests/exams, I find it hard to concentrate.", score: 0 },
  { text: "Before a test/exam, I feel nervous.", score: 0 },
  { text: "During a test/exam, my muscles are tight.", score: 0 },
];
